DELETE https://localhost:5001/clients/6

###
PUT https://localhost:5001/clients
Content-Type: application/json

{
  "id": 6,
  "name": "Samy AS"
}

###
POST https://localhost:5001/clients
Content-Type: application/json

{
  "name": "Samy"
}

###
GET https://localhost:5001/weatherforecast
Accept: */*
Cache-Control: no-cache

###
POST https://localhost:5001/auth/login
Content-Type: application/json

{
  "email": "rafael.gonzalez.1737@gmail.com",
  "password": "123456789"
}

###
GET https://localhost:5001/clients
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM

###
POST https://localhost:5001/sale
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM
Content-Type: application/json

{
  "idClient": 1,
  "total": 100,
  "concepts": [
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    },
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    },
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    },
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    },
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    },
    {
      "idProduct": 3,
      "priceUnit": 10.8,
      "amount": 10,
      "total": 100.0
    }
  ]
}

###
GET https://localhost:5001/business
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM

###
GET https://localhost:5001/suppliers
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM

###
GET https://localhost:5001/products
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM

###
GET https://localhost:5001/sales
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJyYWZhZWwuZ29uemFsZXouMTczN0BnbWFpbC5jb20iLCJuYmYiOjE2MDExMzcyMDIsImV4cCI6MTYwNjMyMTIwMiwiaWF0IjoxNjAxMTM3MjAyfQ.0PoL3ogAZkBi3w9Dgd9YTeTX2k99ec7_XcaRSL67JzM